spring.application.name=products-service-v1
server.port=8081
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30


management.endpoints.web.exposure.include= health,info

management.info.env.enabled = true
info.app.name = products-service-v1
info.app.description = Microservicio de ejemplo Desde github v1
info.app.version = 1.0.0

eureka.client.instance.hostname= localhost
eureka.client.instance.prefer-ip-address=true
